### ISSUE TITLE
More permissive license than GPL3?

### ISSUE THREAD

**Issue by heuer** [elektrofuzzis/ftSwarm#21]
The firmware is licensed under the GPL. 

This in turn means that all programs that use the firmware also fall under the GPL3.

This is a bit unfortunate in my opinion.

A firmware under a license like the LGPL would solve the problem in my opinion. I.e. it would be ensured that the firmware has a copyleft license and programs that use the firmware could choose a different license.

At least that is my understanding of the LGPL, I am not a lawyer. ;)

See also: <https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works>

**Comment by yet-another-fuzzi** [comment]
Changed to MIT

**Comment by Bloeckchengrafik** [comment]
Changed
