### ISSUE TITLE
Docs: Voltmeter -- Clarify port documentation

### ISSUE THREAD

**Issue by heuer** [elektrofuzzis/ftSwarm#27]
https://elektrofuzzis.github.io/ftSwarm/cpp/analog/analog/ states "ftSwarm is able to measure voltages at input FTSWARM_A2 as well."

https://elektrofuzzis.github.io/ftSwarm/cpp/analog/FtSwarmVoltmeter/ states "Voltage measurement can be done using input A2 on the ftSwarm."

The documentation leaves open whether the measurement is only possible on A2 or on every port including A2. The first page says "possible on A2 too" while the second page seems to say it's only possible on A2.

**Comment by yet-another-fuzzi** [comment]
new documentation in place
